server:
  port: 8080
spring:
  #    profiles:
  #        active: dev # 环境设置
  #    application:
  #        name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/xiyo_redis_app?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/xiyo_redis_app?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false
    username: root
    password: 123456
#spring:
#    redis:
#        database: 0
#        host: 127.0.0.1
#        port: 6379
#        password: test
#        lettuce:
#            pool:
#                min-idle: 0
#                max-active: 8
#                max-idle: 8
#                max-wait: -1ms
#        connect-timeout: 30000ms
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    mapper-locations: classpath:com/xiyo/redisQuiz/mapper/xml/*.xml